spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(1iB291mbiqlGVJC5RQeSTYZPmEDGFHc2AGNg/e98cfdrIKgp0fcyR5dDAgKcrG+jPP7UhHLd9XIwP+WdbudoBgcOP5umB6LNpNbfUdAyAUbREMHxmV147w==)
            client-secret: ENC(2ZlPmuO36z6BPwRNoaVo6g//j5lZJM9m4LvNn81+1dyPeredxVC8ya9UA6Q3xFS6)
            scope:
              - profile
              - email
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 1000
  datasource:
    primary:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(RPbpE2JLesHBigkm+x9HXc8mgyWKtwP/QZ73CbPkYmhdSuoAZA97+VLtN+x8KRknQMQEC0WDG5T26kcF3Ug6JPwuPmGaUoLsM7ZPGBd00UzZAwYd4yrUnKKMfh2o7Ezw7GpV8+w/Bw2oTII/f1Bbqb/dYWzVqbCqyDcv9sNFdjhBydFXHzEVNTzQWmzIe1gU)
      username: ENC(2C4Z+DVEBjOHLdTFaaiRDQ==)
      password: ENC(Ru8rn54g8uSVcxbuVPfV+A==)
    second:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(jd2MfzS17cdBiC1ZBWTxV/Nh0rxUmh7NghH+F9ph/Q+sTWUzzluakIKtX+ZJsgjYp0FjD4LLDXt9h9365WJKUFyXbYK+dbsb7hM97d11vxQAiwEIZt3Uw1/DsdHfPDZ+HCNgg+Wou+Wq9Io3c6YffkIHuqHZJu3OtPIAlQiTNXg+TjsqBgGc2A==)
      username: ENC(2C4Z+DVEBjOHLdTFaaiRDQ==)
      password: ENC(Ru8rn54g8uSVcxbuVPfV+A==)
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
cloud:
  aws:
    credentials:
      accessKey: ENC(0k9s6IaVx7piBqiMCc7JZjqEwIvP0t1caffXs/5atNc=)
      secretKey: ENC(I8barg4Cu8UtN0eoQxoWqCznx0/WH4goRGVqZ8AKvwNR9KXVZJ7MxfTTrQer3WUCO9GZ5egxuGE=)
    s3:
      bucket: muntage
    region:
      static: ap-northeast-2
    stack:
      auto: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
custom:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    callback-url: http://localhost:3000/frontend/auth
    scope : https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email
    client-id: ENC(1iB291mbiqlGVJC5RQeSTYZPmEDGFHc2AGNg/e98cfdrIKgp0fcyR5dDAgKcrG+jPP7UhHLd9XIwP+WdbudoBgcOP5umB6LNpNbfUdAyAUbREMHxmV147w==)
    client-secret: ENC(2ZlPmuO36z6BPwRNoaVo6g//j5lZJM9m4LvNn81+1dyPeredxVC8ya9UA6Q3xFS6)
  jwt:
    secretKey: ENC(4eL6R6/CT+2w1ss8z9kbLCGT+TLF4JrAw4HATFWQGA0ZVg53roc2Ej/OOKsI5G/9kBSzPV8dZ5l84UNnKMF8Iw==)
