spring:
  security:
    oauth2:
      client:
        registration:
          #          kakao:
          #            client-id: <your id>
          #            client-secret: <your secret>
          #            redirect-uri: <your url>/login/oauth2/code/kakao
          #            authorization-grant-type: authorization_code
          #            client-authentication-method: POST
          #            client-name: Kakao
          #            scope:
          #              - profile
          #              - account_email
          #          naver:
          #            client-id: <your id>
          #            client-secret: <your secret>
          #            redirect-uri: <your url>/login/oauth2/code/naver
          #            authorization-grant-type: authorization_code
          #            scope:
          #              - name
          #              - email
          google:
            client-id: ENC(1iB291mbiqlGVJC5RQeSTYZPmEDGFHc2AGNg/e98cfdrIKgp0fcyR5dDAgKcrG+jPP7UhHLd9XIwP+WdbudoBgcOP5umB6LNpNbfUdAyAUbREMHxmV147w==)
            client-secret: ENC(2ZlPmuO36z6BPwRNoaVo6g//j5lZJM9m4LvNn81+1dyPeredxVC8ya9UA6Q3xFS6)
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 1000
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(OiAQxhCYyIj06VasfHOao4T48FtbXRn99opP1tJBtrTRcf996/oWvutZQh8A9O0XkVcB1dfmC+4K2WFF2eE0k8zZoeksVCt6Z8IbyozMHntUmURTODozSLrYBwV582sFG7vM+zEcsLVIytvYShHpBG5RQbBlHnobIHtL0SXr6a9VXBEjVVs7vKJhTzIQNS2V)
    username: ENC(2C4Z+DVEBjOHLdTFaaiRDQ==)
    password: ENC(Ru8rn54g8uSVcxbuVPfV+A==)
cloud:
  aws:
    credentials:
      accessKey: ENC(0k9s6IaVx7piBqiMCc7JZjqEwIvP0t1caffXs/5atNc=)
      secretKey: ENC(I8barg4Cu8UtN0eoQxoWqCznx0/WH4goRGVqZ8AKvwNR9KXVZJ7MxfTTrQer3WUCO9GZ5egxuGE=)
    s3:
      bucket: muntage
    region:
      static: ap-northeast-2
    stack:
      auto: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
