spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(1iB291mbiqlGVJC5RQeSTYZPmEDGFHc2AGNg/e98cfdrIKgp0fcyR5dDAgKcrG+jPP7UhHLd9XIwP+WdbudoBgcOP5umB6LNpNbfUdAyAUbREMHxmV147w==)
            client-secret: ENC(2ZlPmuO36z6BPwRNoaVo6g//j5lZJM9m4LvNn81+1dyPeredxVC8ya9UA6Q3xFS6)
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 1000
  datasource:
    primary:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(wYbMzMFkATJAbPXdd+tTgE22KK6G2fJUwdiNApRF58DHvijV62P07w2krfquB2+KirYbHI0iLd9xEEEptzZv1ISWCcyP9Fc2tlxp32n0fXOWB7BYrwD34LVN/JkVtP79qXqXZvCknhdrITiWbARNPrbcb6zhbFevAcliH7ciGYXxpbpCiF3AkPQ+WUvFDMjk)
      username: ENC(2C4Z+DVEBjOHLdTFaaiRDQ==)
      password: ENC(Ru8rn54g8uSVcxbuVPfV+A==)
    second:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ENC(jd2MfzS17cdBiC1ZBWTxV/Nh0rxUmh7NghH+F9ph/Q+sTWUzzluakIKtX+ZJsgjYp0FjD4LLDXt9h9365WJKUFyXbYK+dbsb7hM97d11vxQAiwEIZt3Uw1/DsdHfPDZ+HCNgg+Wou+Wq9Io3c6YffkIHuqHZJu3OtPIAlQiTNXg+TjsqBgGc2A==)
      username: ENC(2C4Z+DVEBjOHLdTFaaiRDQ==)
      password: ENC(Ru8rn54g8uSVcxbuVPfV+A==)
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
custom:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    callback-url : http://localhost:8080/api/v1/oauth
    scope : https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email
    client-id: ENC(1iB291mbiqlGVJC5RQeSTYZPmEDGFHc2AGNg/e98cfdrIKgp0fcyR5dDAgKcrG+jPP7UhHLd9XIwP+WdbudoBgcOP5umB6LNpNbfUdAyAUbREMHxmV147w==)
    client-secret: ENC(2ZlPmuO36z6BPwRNoaVo6g//j5lZJM9m4LvNn81+1dyPeredxVC8ya9UA6Q3xFS6)
  jwt:
    secretKey: ENC(4eL6R6/CT+2w1ss8z9kbLCGT+TLF4JrAw4HATFWQGA0ZVg53roc2Ej/OOKsI5G/9kBSzPV8dZ5l84UNnKMF8Iw==)